CREATE TABLE polyperc_projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_name TEXT NOT NULL,
    creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_edited TIMESTAMPTZ DEFAULT now() NOT NULL,
);

