CREATE TABLE polyperc_patterns (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pattern_name TEXT NOT NULL,
    
    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,
    
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_edited TIMESTAMPTZ DEFAULT now() NOT NULL,

    tempo INTEGER NOT NULL DEFAULT 120;
    ratio TEXT DEFAULT '1:1',
    source TEXT DEFAULT 'master'

    sound TEXT,
    is_playing BOOLEAN DEFAULT FALSE,
    current_beat INTEGER NOT NULL DEFAULT 0,

    pattern_length INTEGER NOT NULL,
    active_beats INTEGER NOT NULL,
    rotation INTEGER NOT NULL DEFAULT 0,
    is_reversed BOOLEAN DEFAULT FALSE,
    is_opposite BOOLEAN DEFAULT FALSE,
);

