CREATE TABLE polyperc_patterns (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pattern_name TEXT,
    
    project_id INTEGER REFERENCES polyperc_projects(id) ON DELETE CASCADE,
    
    date_created TIMESTAMPTZ DEFAULT now(),
    date_edited TIMESTAMPTZ DEFAULT now() NOT NULL,

    is_expanded BOOLEAN DEFAULT TRUE,

    tempo INTEGER DEFAULT 120,
    ratio TEXT DEFAULT '1:1',
    source TEXT DEFAULT 'master',
    
    sound TEXT,
    is_muted BOOLEAN DEFAULT FALSE,
    is_soloed BOOLEAN DEFAULT FALSE,
    is_playing BOOLEAN DEFAULT FALSE,
    current_beat INTEGER DEFAULT 0,
    volume INTEGER NOT NULL DEFAULT -20,

    pattern_length INTEGER,
    active_beats INTEGER,
    rotation INTEGER NOT NULL DEFAULT 0,
    is_reversed BOOLEAN DEFAULT FALSE,
    is_opposite BOOLEAN DEFAULT FALSE,

    pattern INTEGER[],
    original_pattern INTEGER[]
);